sudo: required

services:
  - docker

language: node_js
node_js:
- '8'

dist: trusty
sudo: false

cache:
  directories:
  - $HOME/.npm
  - node_modules

script:
- npm install --no-optional
- npm run test
- npm run build
- docker build -t crviz -f Dockerfile .
- docker build -t crviz-gh -f Dockerfile.gh .